#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 72
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 10
#define PRODUCTION_ID_COUNT 3

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_LF = 2,
  anon_sym_type = 3,
  anon_sym_EQ = 4,
  anon_sym_PIPE = 5,
  aux_sym_constructor_name_token1 = 6,
  aux_sym_type_parameter_token1 = 7,
  anon_sym_alias = 8,
  anon_sym_LBRACE = 9,
  anon_sym_COMMA = 10,
  anon_sym_RBRACE = 11,
  anon_sym_COLON = 12,
  sym_string = 13,
  sym_source_file = 14,
  sym_type_definition = 15,
  sym_sum_type = 16,
  sym_constructor = 17,
  sym_constructor_name = 18,
  sym_type_identifier = 19,
  sym_type_parameter = 20,
  sym_value_definition = 21,
  sym_parameter = 22,
  sym_value_identifier = 23,
  sym_product_type = 24,
  sym_name_type_pair = 25,
  sym_field_identifier = 26,
  sym_expression = 27,
  aux_sym_source_file_repeat1 = 28,
  aux_sym_sum_type_repeat1 = 29,
  aux_sym_sum_type_repeat2 = 30,
  aux_sym_constructor_repeat1 = 31,
  aux_sym_value_definition_repeat1 = 32,
  aux_sym_product_type_repeat1 = 33,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_LF] = "\n",
  [anon_sym_type] = "type",
  [anon_sym_EQ] = "=",
  [anon_sym_PIPE] = "|",
  [aux_sym_constructor_name_token1] = "constructor_name_token1",
  [aux_sym_type_parameter_token1] = "type_parameter_token1",
  [anon_sym_alias] = "alias",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [sym_string] = "string",
  [sym_source_file] = "source_file",
  [sym_type_definition] = "type_definition",
  [sym_sum_type] = "sum_type",
  [sym_constructor] = "constructor",
  [sym_constructor_name] = "constructor_name",
  [sym_type_identifier] = "type_identifier",
  [sym_type_parameter] = "type_parameter",
  [sym_value_definition] = "value_definition",
  [sym_parameter] = "parameter",
  [sym_value_identifier] = "value_identifier",
  [sym_product_type] = "product_type",
  [sym_name_type_pair] = "name_type_pair",
  [sym_field_identifier] = "field_identifier",
  [sym_expression] = "expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_sum_type_repeat1] = "sum_type_repeat1",
  [aux_sym_sum_type_repeat2] = "sum_type_repeat2",
  [aux_sym_constructor_repeat1] = "constructor_repeat1",
  [aux_sym_value_definition_repeat1] = "value_definition_repeat1",
  [aux_sym_product_type_repeat1] = "product_type_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [aux_sym_constructor_name_token1] = aux_sym_constructor_name_token1,
  [aux_sym_type_parameter_token1] = aux_sym_type_parameter_token1,
  [anon_sym_alias] = anon_sym_alias,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_string] = sym_string,
  [sym_source_file] = sym_source_file,
  [sym_type_definition] = sym_type_definition,
  [sym_sum_type] = sym_sum_type,
  [sym_constructor] = sym_constructor,
  [sym_constructor_name] = sym_constructor_name,
  [sym_type_identifier] = sym_type_identifier,
  [sym_type_parameter] = sym_type_parameter,
  [sym_value_definition] = sym_value_definition,
  [sym_parameter] = sym_parameter,
  [sym_value_identifier] = sym_value_identifier,
  [sym_product_type] = sym_product_type,
  [sym_name_type_pair] = sym_name_type_pair,
  [sym_field_identifier] = sym_field_identifier,
  [sym_expression] = sym_expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_sum_type_repeat1] = aux_sym_sum_type_repeat1,
  [aux_sym_sum_type_repeat2] = aux_sym_sum_type_repeat2,
  [aux_sym_constructor_repeat1] = aux_sym_constructor_repeat1,
  [aux_sym_value_definition_repeat1] = aux_sym_value_definition_repeat1,
  [aux_sym_product_type_repeat1] = aux_sym_product_type_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_constructor_name_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_parameter_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_alias] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_type_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_sum_type] = {
    .visible = true,
    .named = true,
  },
  [sym_constructor] = {
    .visible = true,
    .named = true,
  },
  [sym_constructor_name] = {
    .visible = true,
    .named = true,
  },
  [sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_type_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_value_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_value_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_product_type] = {
    .visible = true,
    .named = true,
  },
  [sym_name_type_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_field_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sum_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sum_type_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_constructor_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_product_type_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_include = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_include] = "include",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_include, 4},
    {field_include, 5},
  [2] =
    {field_include, 5},
    {field_include, 6},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 7,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 24,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '"', 2,
        '#', 5,
        ',', 21,
        ':', 23,
        '=', 8,
        'a', 14,
        't', 17,
        '{', 20,
        '|', 9,
        '}', 22,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('b' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(10);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '#') ADVANCE(5);
      if (lookahead == '|') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(10);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(5);
      if (lookahead == ',') ADVANCE(21);
      if (lookahead == '=') ADVANCE(8);
      if (lookahead == '}') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_type);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_constructor_name_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_type_parameter_token1);
      if (lookahead == 'a') ADVANCE(16);
      if (('b' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_type_parameter_token1);
      if (lookahead == 'e') ADVANCE(7);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_type_parameter_token1);
      if (lookahead == 'i') ADVANCE(11);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_type_parameter_token1);
      if (lookahead == 'l') ADVANCE(13);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_type_parameter_token1);
      if (lookahead == 'p') ADVANCE(12);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_type_parameter_token1);
      if (lookahead == 's') ADVANCE(19);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_type_parameter_token1);
      if (lookahead == 'y') ADVANCE(15);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_type_parameter_token1);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_alias);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [aux_sym_constructor_name_token1] = ACTIONS(1),
    [aux_sym_type_parameter_token1] = ACTIONS(1),
    [anon_sym_alias] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(71),
    [sym_type_definition] = STATE(3),
    [sym_sum_type] = STATE(65),
    [sym_value_definition] = STATE(3),
    [sym_value_identifier] = STATE(8),
    [sym_product_type] = STATE(65),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_type] = ACTIONS(7),
    [aux_sym_type_parameter_token1] = ACTIONS(9),
    [anon_sym_alias] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      anon_sym_type,
    ACTIONS(18), 1,
      aux_sym_type_parameter_token1,
    ACTIONS(21), 1,
      anon_sym_alias,
    STATE(8), 1,
      sym_value_identifier,
    STATE(65), 2,
      sym_sum_type,
      sym_product_type,
    STATE(2), 3,
      sym_type_definition,
      sym_value_definition,
      aux_sym_source_file_repeat1,
  [28] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_type,
    ACTIONS(9), 1,
      aux_sym_type_parameter_token1,
    ACTIONS(11), 1,
      anon_sym_alias,
    ACTIONS(24), 1,
      ts_builtin_sym_end,
    STATE(8), 1,
      sym_value_identifier,
    STATE(65), 2,
      sym_sum_type,
      sym_product_type,
    STATE(2), 3,
      sym_type_definition,
      sym_value_definition,
      aux_sym_source_file_repeat1,
  [56] = 6,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(28), 1,
      anon_sym_LF,
    ACTIONS(30), 1,
      anon_sym_PIPE,
    ACTIONS(32), 1,
      aux_sym_constructor_name_token1,
    ACTIONS(34), 1,
      aux_sym_type_parameter_token1,
    STATE(6), 3,
      sym_type_identifier,
      sym_type_parameter,
      aux_sym_constructor_repeat1,
  [77] = 6,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(36), 1,
      anon_sym_LF,
    ACTIONS(38), 1,
      anon_sym_PIPE,
    ACTIONS(40), 1,
      aux_sym_constructor_name_token1,
    ACTIONS(43), 1,
      aux_sym_type_parameter_token1,
    STATE(5), 3,
      sym_type_identifier,
      sym_type_parameter,
      aux_sym_constructor_repeat1,
  [98] = 6,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(32), 1,
      aux_sym_constructor_name_token1,
    ACTIONS(34), 1,
      aux_sym_type_parameter_token1,
    ACTIONS(46), 1,
      anon_sym_LF,
    ACTIONS(48), 1,
      anon_sym_PIPE,
    STATE(5), 3,
      sym_type_identifier,
      sym_type_parameter,
      aux_sym_constructor_repeat1,
  [119] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 4,
      anon_sym_EQ,
      aux_sym_type_parameter_token1,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [129] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 1,
      anon_sym_EQ,
    ACTIONS(54), 1,
      aux_sym_type_parameter_token1,
    STATE(11), 2,
      sym_parameter,
      aux_sym_value_definition_repeat1,
  [143] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_EQ,
    ACTIONS(58), 1,
      aux_sym_type_parameter_token1,
    STATE(14), 2,
      sym_type_parameter,
      aux_sym_sum_type_repeat1,
  [157] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    ACTIONS(62), 3,
      anon_sym_type,
      aux_sym_type_parameter_token1,
      anon_sym_alias,
  [169] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 1,
      aux_sym_type_parameter_token1,
    ACTIONS(64), 1,
      anon_sym_EQ,
    STATE(22), 2,
      sym_parameter,
      aux_sym_value_definition_repeat1,
  [183] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      aux_sym_type_parameter_token1,
    ACTIONS(66), 1,
      anon_sym_EQ,
    STATE(13), 2,
      sym_type_parameter,
      aux_sym_sum_type_repeat1,
  [197] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      aux_sym_type_parameter_token1,
    ACTIONS(68), 1,
      anon_sym_EQ,
    STATE(19), 2,
      sym_type_parameter,
      aux_sym_sum_type_repeat1,
  [211] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      aux_sym_type_parameter_token1,
    ACTIONS(70), 1,
      anon_sym_EQ,
    STATE(19), 2,
      sym_type_parameter,
      aux_sym_sum_type_repeat1,
  [225] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
    ACTIONS(74), 3,
      anon_sym_type,
      aux_sym_type_parameter_token1,
      anon_sym_alias,
  [237] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    ACTIONS(78), 3,
      anon_sym_type,
      aux_sym_type_parameter_token1,
      anon_sym_alias,
  [249] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      aux_sym_type_parameter_token1,
    STATE(32), 1,
      sym_name_type_pair,
    STATE(61), 1,
      sym_type_parameter,
    STATE(64), 1,
      sym_field_identifier,
  [265] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      ts_builtin_sym_end,
    ACTIONS(84), 3,
      anon_sym_type,
      aux_sym_type_parameter_token1,
      anon_sym_alias,
  [277] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      anon_sym_EQ,
    ACTIONS(88), 1,
      aux_sym_type_parameter_token1,
    STATE(19), 2,
      sym_type_parameter,
      aux_sym_sum_type_repeat1,
  [291] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      aux_sym_type_parameter_token1,
    STATE(37), 1,
      sym_name_type_pair,
    STATE(59), 1,
      sym_type_parameter,
    STATE(64), 1,
      sym_field_identifier,
  [307] = 3,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_LF,
    ACTIONS(93), 3,
      anon_sym_PIPE,
      aux_sym_constructor_name_token1,
      aux_sym_type_parameter_token1,
  [319] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_EQ,
    ACTIONS(97), 1,
      aux_sym_type_parameter_token1,
    STATE(22), 2,
      sym_parameter,
      aux_sym_value_definition_repeat1,
  [333] = 3,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(50), 1,
      anon_sym_LF,
    ACTIONS(100), 3,
      anon_sym_PIPE,
      aux_sym_constructor_name_token1,
      aux_sym_type_parameter_token1,
  [345] = 3,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_LF,
    ACTIONS(104), 3,
      anon_sym_PIPE,
      aux_sym_constructor_name_token1,
      aux_sym_type_parameter_token1,
  [357] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_COMMA,
    ACTIONS(108), 1,
      anon_sym_RBRACE,
    STATE(39), 1,
      aux_sym_product_type_repeat1,
  [370] = 4,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(110), 1,
      anon_sym_LF,
    ACTIONS(112), 1,
      anon_sym_PIPE,
    STATE(30), 1,
      aux_sym_sum_type_repeat2,
  [383] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      aux_sym_constructor_name_token1,
    STATE(4), 1,
      sym_constructor_name,
    STATE(31), 1,
      sym_constructor,
  [396] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      aux_sym_constructor_name_token1,
    STATE(4), 1,
      sym_constructor_name,
    STATE(26), 1,
      sym_constructor,
  [409] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      aux_sym_constructor_name_token1,
    STATE(4), 1,
      sym_constructor_name,
    STATE(54), 1,
      sym_constructor,
  [422] = 4,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_PIPE,
    ACTIONS(116), 1,
      anon_sym_LF,
    STATE(33), 1,
      aux_sym_sum_type_repeat2,
  [435] = 4,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_PIPE,
    ACTIONS(116), 1,
      anon_sym_LF,
    STATE(44), 1,
      aux_sym_sum_type_repeat2,
  [448] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_COMMA,
    ACTIONS(118), 1,
      anon_sym_RBRACE,
    STATE(36), 1,
      aux_sym_product_type_repeat1,
  [461] = 4,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(120), 1,
      anon_sym_LF,
    ACTIONS(122), 1,
      anon_sym_PIPE,
    STATE(33), 1,
      aux_sym_sum_type_repeat2,
  [474] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      aux_sym_type_parameter_token1,
    STATE(38), 1,
      sym_name_type_pair,
    STATE(64), 1,
      sym_field_identifier,
  [487] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      aux_sym_type_parameter_token1,
    STATE(50), 1,
      sym_name_type_pair,
    STATE(64), 1,
      sym_field_identifier,
  [500] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_COMMA,
    ACTIONS(127), 1,
      anon_sym_RBRACE,
    STATE(39), 1,
      aux_sym_product_type_repeat1,
  [513] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_COMMA,
    ACTIONS(127), 1,
      anon_sym_RBRACE,
    STATE(41), 1,
      aux_sym_product_type_repeat1,
  [526] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_COMMA,
    ACTIONS(129), 1,
      anon_sym_RBRACE,
    STATE(25), 1,
      aux_sym_product_type_repeat1,
  [539] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(134), 1,
      anon_sym_RBRACE,
    STATE(39), 1,
      aux_sym_product_type_repeat1,
  [552] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      aux_sym_type_parameter_token1,
    STATE(42), 1,
      sym_name_type_pair,
    STATE(64), 1,
      sym_field_identifier,
  [565] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_COMMA,
    ACTIONS(136), 1,
      anon_sym_RBRACE,
    STATE(39), 1,
      aux_sym_product_type_repeat1,
  [578] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_COMMA,
    ACTIONS(138), 1,
      anon_sym_RBRACE,
    STATE(43), 1,
      aux_sym_product_type_repeat1,
  [591] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_COMMA,
    ACTIONS(140), 1,
      anon_sym_RBRACE,
    STATE(39), 1,
      aux_sym_product_type_repeat1,
  [604] = 4,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_PIPE,
    ACTIONS(142), 1,
      anon_sym_LF,
    STATE(33), 1,
      aux_sym_sum_type_repeat2,
  [617] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      aux_sym_constructor_name_token1,
    STATE(12), 1,
      sym_type_identifier,
  [627] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 2,
      anon_sym_EQ,
      aux_sym_type_parameter_token1,
  [635] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 2,
      anon_sym_EQ,
      aux_sym_type_parameter_token1,
  [643] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      aux_sym_constructor_name_token1,
    STATE(52), 1,
      sym_type_identifier,
  [653] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_PIPE,
    ACTIONS(148), 1,
      anon_sym_COLON,
  [663] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [671] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      sym_string,
    STATE(18), 1,
      sym_expression,
  [681] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [689] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      sym_string,
    STATE(16), 1,
      sym_expression,
  [699] = 3,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(120), 1,
      anon_sym_LF,
    ACTIONS(154), 1,
      anon_sym_PIPE,
  [709] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      aux_sym_constructor_name_token1,
    STATE(9), 1,
      sym_type_identifier,
  [719] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 2,
      anon_sym_EQ,
      aux_sym_type_parameter_token1,
  [727] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      anon_sym_LBRACE,
  [734] = 2,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(160), 1,
      anon_sym_LF,
  [741] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_PIPE,
  [748] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      anon_sym_COLON,
  [755] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_PIPE,
  [762] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 1,
      anon_sym_LBRACE,
  [769] = 2,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_LF,
  [776] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      anon_sym_COLON,
  [783] = 2,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(172), 1,
      anon_sym_LF,
  [790] = 2,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(174), 1,
      anon_sym_LF,
  [797] = 2,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_LF,
  [804] = 2,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_LF,
  [811] = 2,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(180), 1,
      anon_sym_LF,
  [818] = 2,
    ACTIONS(26), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_LF,
  [825] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 28,
  [SMALL_STATE(4)] = 56,
  [SMALL_STATE(5)] = 77,
  [SMALL_STATE(6)] = 98,
  [SMALL_STATE(7)] = 119,
  [SMALL_STATE(8)] = 129,
  [SMALL_STATE(9)] = 143,
  [SMALL_STATE(10)] = 157,
  [SMALL_STATE(11)] = 169,
  [SMALL_STATE(12)] = 183,
  [SMALL_STATE(13)] = 197,
  [SMALL_STATE(14)] = 211,
  [SMALL_STATE(15)] = 225,
  [SMALL_STATE(16)] = 237,
  [SMALL_STATE(17)] = 249,
  [SMALL_STATE(18)] = 265,
  [SMALL_STATE(19)] = 277,
  [SMALL_STATE(20)] = 291,
  [SMALL_STATE(21)] = 307,
  [SMALL_STATE(22)] = 319,
  [SMALL_STATE(23)] = 333,
  [SMALL_STATE(24)] = 345,
  [SMALL_STATE(25)] = 357,
  [SMALL_STATE(26)] = 370,
  [SMALL_STATE(27)] = 383,
  [SMALL_STATE(28)] = 396,
  [SMALL_STATE(29)] = 409,
  [SMALL_STATE(30)] = 422,
  [SMALL_STATE(31)] = 435,
  [SMALL_STATE(32)] = 448,
  [SMALL_STATE(33)] = 461,
  [SMALL_STATE(34)] = 474,
  [SMALL_STATE(35)] = 487,
  [SMALL_STATE(36)] = 500,
  [SMALL_STATE(37)] = 513,
  [SMALL_STATE(38)] = 526,
  [SMALL_STATE(39)] = 539,
  [SMALL_STATE(40)] = 552,
  [SMALL_STATE(41)] = 565,
  [SMALL_STATE(42)] = 578,
  [SMALL_STATE(43)] = 591,
  [SMALL_STATE(44)] = 604,
  [SMALL_STATE(45)] = 617,
  [SMALL_STATE(46)] = 627,
  [SMALL_STATE(47)] = 635,
  [SMALL_STATE(48)] = 643,
  [SMALL_STATE(49)] = 653,
  [SMALL_STATE(50)] = 663,
  [SMALL_STATE(51)] = 671,
  [SMALL_STATE(52)] = 681,
  [SMALL_STATE(53)] = 689,
  [SMALL_STATE(54)] = 699,
  [SMALL_STATE(55)] = 709,
  [SMALL_STATE(56)] = 719,
  [SMALL_STATE(57)] = 727,
  [SMALL_STATE(58)] = 734,
  [SMALL_STATE(59)] = 741,
  [SMALL_STATE(60)] = 748,
  [SMALL_STATE(61)] = 755,
  [SMALL_STATE(62)] = 762,
  [SMALL_STATE(63)] = 769,
  [SMALL_STATE(64)] = 776,
  [SMALL_STATE(65)] = 783,
  [SMALL_STATE(66)] = 790,
  [SMALL_STATE(67)] = 797,
  [SMALL_STATE(68)] = 804,
  [SMALL_STATE(69)] = 811,
  [SMALL_STATE(70)] = 818,
  [SMALL_STATE(71)] = 825,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [18] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [26] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constructor, 1, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constructor, 1, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [34] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_constructor_repeat1, 2, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_constructor_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_constructor_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_constructor_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constructor, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constructor, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_identifier, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_definition, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_definition, 3, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value_definition, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_definition, 4, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value_definition, 4, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sum_type_repeat1, 2, 0, 0),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sum_type_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constructor_name, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constructor_name, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_value_definition_repeat1, 2, 0, 0),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_identifier, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameter, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_parameter, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sum_type, 4, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sum_type, 5, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sum_type_repeat2, 2, 0, 0),
  [122] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_sum_type_repeat2, 2, 0, 0), SHIFT_REPEAT(29),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [131] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_product_type_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_product_type_repeat1, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sum_type, 6, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_identifier, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_identifier, 1, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name_type_pair, 3, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_sum_type_repeat2, 2, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 1, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_product_type, 6, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_product_type, 7, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_product_type, 8, 0, 1),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_product_type, 8, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_product_type, 9, 0, 2),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_product_type, 9, 0, 1),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_product_type, 10, 0, 2),
  [184] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_oakly(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
