#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 90
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 2

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_type = 2,
  anon_sym_EQ = 3,
  anon_sym_PIPE = 4,
  sym_parameter = 5,
  anon_sym_alias = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  anon_sym_LBRACE = 9,
  anon_sym_COMMA = 10,
  anon_sym_RBRACE = 11,
  anon_sym_COLON = 12,
  sym_string = 13,
  aux_sym_constructor_name_token1 = 14,
  aux_sym_type_parameter_token1 = 15,
  sym_source_file = 16,
  sym_type_definition = 17,
  sym_sum_type_definition = 18,
  sym_constructor = 19,
  sym_value_definition = 20,
  sym_alias_definition = 21,
  sym_type = 22,
  sym_sum_type = 23,
  sym_product_type = 24,
  sym_name_type_pair = 25,
  sym_expression = 26,
  sym_constructor_name = 27,
  sym_type_identifier = 28,
  sym_type_parameter = 29,
  sym_value_identifier = 30,
  sym_field_identifier = 31,
  aux_sym_source_file_repeat1 = 32,
  aux_sym_sum_type_definition_repeat1 = 33,
  aux_sym_sum_type_definition_repeat2 = 34,
  aux_sym_constructor_repeat1 = 35,
  aux_sym_value_definition_repeat1 = 36,
  aux_sym_product_type_repeat1 = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_type] = "type",
  [anon_sym_EQ] = "=",
  [anon_sym_PIPE] = "|",
  [sym_parameter] = "parameter",
  [anon_sym_alias] = "alias",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [sym_string] = "string",
  [aux_sym_constructor_name_token1] = "constructor_name_token1",
  [aux_sym_type_parameter_token1] = "type_parameter_token1",
  [sym_source_file] = "source_file",
  [sym_type_definition] = "type_definition",
  [sym_sum_type_definition] = "sum_type_definition",
  [sym_constructor] = "constructor",
  [sym_value_definition] = "value_definition",
  [sym_alias_definition] = "alias_definition",
  [sym_type] = "type",
  [sym_sum_type] = "sum_type",
  [sym_product_type] = "product_type",
  [sym_name_type_pair] = "name_type_pair",
  [sym_expression] = "expression",
  [sym_constructor_name] = "constructor_name",
  [sym_type_identifier] = "type_identifier",
  [sym_type_parameter] = "type_parameter",
  [sym_value_identifier] = "value_identifier",
  [sym_field_identifier] = "field_identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_sum_type_definition_repeat1] = "sum_type_definition_repeat1",
  [aux_sym_sum_type_definition_repeat2] = "sum_type_definition_repeat2",
  [aux_sym_constructor_repeat1] = "constructor_repeat1",
  [aux_sym_value_definition_repeat1] = "value_definition_repeat1",
  [aux_sym_product_type_repeat1] = "product_type_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_parameter] = sym_parameter,
  [anon_sym_alias] = anon_sym_alias,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_string] = sym_string,
  [aux_sym_constructor_name_token1] = aux_sym_constructor_name_token1,
  [aux_sym_type_parameter_token1] = aux_sym_type_parameter_token1,
  [sym_source_file] = sym_source_file,
  [sym_type_definition] = sym_type_definition,
  [sym_sum_type_definition] = sym_sum_type_definition,
  [sym_constructor] = sym_constructor,
  [sym_value_definition] = sym_value_definition,
  [sym_alias_definition] = sym_alias_definition,
  [sym_type] = sym_type,
  [sym_sum_type] = sym_sum_type,
  [sym_product_type] = sym_product_type,
  [sym_name_type_pair] = sym_name_type_pair,
  [sym_expression] = sym_expression,
  [sym_constructor_name] = sym_constructor_name,
  [sym_type_identifier] = sym_type_identifier,
  [sym_type_parameter] = sym_type_parameter,
  [sym_value_identifier] = sym_value_identifier,
  [sym_field_identifier] = sym_field_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_sum_type_definition_repeat1] = aux_sym_sum_type_definition_repeat1,
  [aux_sym_sum_type_definition_repeat2] = aux_sym_sum_type_definition_repeat2,
  [aux_sym_constructor_repeat1] = aux_sym_constructor_repeat1,
  [aux_sym_value_definition_repeat1] = aux_sym_value_definition_repeat1,
  [aux_sym_product_type_repeat1] = aux_sym_product_type_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_alias] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_constructor_name_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_parameter_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_type_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_sum_type_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_constructor] = {
    .visible = true,
    .named = true,
  },
  [sym_value_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_alias_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_sum_type] = {
    .visible = true,
    .named = true,
  },
  [sym_product_type] = {
    .visible = true,
    .named = true,
  },
  [sym_name_type_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_constructor_name] = {
    .visible = true,
    .named = true,
  },
  [sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_type_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_value_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_field_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sum_type_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sum_type_definition_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_constructor_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_product_type_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_include = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_include] = "include",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_include, 1},
    {field_include, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 6,
  [8] = 5,
  [9] = 5,
  [10] = 4,
  [11] = 6,
  [12] = 6,
  [13] = 5,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 22,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 29,
  [31] = 27,
  [32] = 16,
  [33] = 14,
  [34] = 15,
  [35] = 18,
  [36] = 19,
  [37] = 17,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 47,
  [57] = 57,
  [58] = 58,
  [59] = 57,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 66,
  [71] = 63,
  [72] = 61,
  [73] = 73,
  [74] = 73,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 83,
  [88] = 88,
  [89] = 84,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '"', 1,
        '#', 6,
        '(', 22,
        ')', 23,
        ',', 25,
        ':', 27,
        '=', 9,
        'a', 14,
        't', 17,
        '{', 24,
        '|', 10,
        '}', 26,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('b' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(29);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(6);
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == ')') ADVANCE(23);
      if (lookahead == ',') ADVANCE(25);
      if (lookahead == '=') ADVANCE(9);
      if (lookahead == '{') ADVANCE(24);
      if (lookahead == '}') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(29);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(6);
      if (lookahead == '=') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 4:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '#', 6,
        '(', 22,
        ')', 23,
        ',', 25,
        'a', 33,
        't', 36,
        '{', 24,
        '|', 10,
        '}', 26,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4);
      if (('b' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(29);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_type);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(37);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_type);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_parameter);
      if (lookahead == 'a') ADVANCE(16);
      if (('b' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(37);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_parameter);
      if (lookahead == 'e') ADVANCE(7);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(37);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_parameter);
      if (lookahead == 'i') ADVANCE(11);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(37);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_parameter);
      if (lookahead == 'l') ADVANCE(13);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(37);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_parameter);
      if (lookahead == 'p') ADVANCE(12);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(37);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_parameter);
      if (lookahead == 's') ADVANCE(20);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(37);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_parameter);
      if (lookahead == 'y') ADVANCE(15);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(37);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_parameter);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(37);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_parameter);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_alias);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(37);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_alias);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_constructor_name_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_type_parameter_token1);
      if (lookahead == 'a') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_type_parameter_token1);
      if (lookahead == 'e') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_type_parameter_token1);
      if (lookahead == 'i') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_type_parameter_token1);
      if (lookahead == 'l') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_type_parameter_token1);
      if (lookahead == 'p') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_type_parameter_token1);
      if (lookahead == 's') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_type_parameter_token1);
      if (lookahead == 'y') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_type_parameter_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 4},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 4},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 4},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 4},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 3},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_parameter] = ACTIONS(1),
    [anon_sym_alias] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [aux_sym_constructor_name_token1] = ACTIONS(1),
    [aux_sym_type_parameter_token1] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(86),
    [sym_type_definition] = STATE(21),
    [sym_sum_type_definition] = STATE(45),
    [sym_value_definition] = STATE(21),
    [sym_alias_definition] = STATE(45),
    [sym_value_identifier] = STATE(69),
    [aux_sym_source_file_repeat1] = STATE(21),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_type] = ACTIONS(7),
    [anon_sym_alias] = ACTIONS(9),
    [aux_sym_type_parameter_token1] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      aux_sym_constructor_name_token1,
    ACTIONS(23), 1,
      aux_sym_type_parameter_token1,
    STATE(6), 1,
      sym_type_identifier,
    ACTIONS(13), 2,
      ts_builtin_sym_end,
      anon_sym_PIPE,
    ACTIONS(15), 2,
      anon_sym_type,
      anon_sym_alias,
    STATE(4), 2,
      sym_type,
      aux_sym_constructor_repeat1,
    STATE(14), 3,
      sym_sum_type,
      sym_product_type,
      sym_type_parameter,
  [36] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      aux_sym_constructor_name_token1,
    ACTIONS(30), 1,
      aux_sym_type_parameter_token1,
    STATE(6), 1,
      sym_type_identifier,
    ACTIONS(26), 2,
      ts_builtin_sym_end,
      anon_sym_PIPE,
    ACTIONS(28), 2,
      anon_sym_type,
      anon_sym_alias,
    STATE(2), 2,
      sym_type,
      aux_sym_constructor_repeat1,
    STATE(14), 3,
      sym_sum_type,
      sym_product_type,
      sym_type_parameter,
  [72] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(43), 1,
      aux_sym_constructor_name_token1,
    ACTIONS(46), 1,
      aux_sym_type_parameter_token1,
    STATE(6), 1,
      sym_type_identifier,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      anon_sym_PIPE,
    ACTIONS(35), 2,
      anon_sym_type,
      anon_sym_alias,
    STATE(4), 2,
      sym_type,
      aux_sym_constructor_repeat1,
    STATE(14), 3,
      sym_sum_type,
      sym_product_type,
      sym_type_parameter,
  [108] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      aux_sym_constructor_name_token1,
    ACTIONS(62), 1,
      aux_sym_type_parameter_token1,
    STATE(6), 1,
      sym_type_identifier,
    ACTIONS(49), 2,
      ts_builtin_sym_end,
      anon_sym_PIPE,
    ACTIONS(51), 2,
      anon_sym_type,
      anon_sym_alias,
    STATE(4), 2,
      sym_type,
      aux_sym_constructor_repeat1,
    STATE(14), 3,
      sym_sum_type,
      sym_product_type,
      sym_type_parameter,
  [144] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 1,
      aux_sym_constructor_name_token1,
    ACTIONS(78), 1,
      aux_sym_type_parameter_token1,
    STATE(6), 1,
      sym_type_identifier,
    ACTIONS(65), 2,
      ts_builtin_sym_end,
      anon_sym_PIPE,
    ACTIONS(67), 2,
      anon_sym_type,
      anon_sym_alias,
    STATE(5), 2,
      sym_type,
      aux_sym_constructor_repeat1,
    STATE(14), 3,
      sym_sum_type,
      sym_product_type,
      sym_type_parameter,
  [180] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      aux_sym_constructor_name_token1,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
    ACTIONS(78), 1,
      aux_sym_type_parameter_token1,
    STATE(6), 1,
      sym_type_identifier,
    ACTIONS(67), 2,
      anon_sym_type,
      anon_sym_alias,
    STATE(8), 2,
      sym_type,
      aux_sym_constructor_repeat1,
    STATE(14), 3,
      sym_sum_type,
      sym_product_type,
      sym_type_parameter,
  [215] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      aux_sym_constructor_name_token1,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(62), 1,
      aux_sym_type_parameter_token1,
    STATE(6), 1,
      sym_type_identifier,
    ACTIONS(51), 2,
      anon_sym_type,
      anon_sym_alias,
    STATE(4), 2,
      sym_type,
      aux_sym_constructor_repeat1,
    STATE(14), 3,
      sym_sum_type,
      sym_product_type,
      sym_type_parameter,
  [250] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 1,
      anon_sym_LBRACE,
    ACTIONS(85), 1,
      aux_sym_constructor_name_token1,
    ACTIONS(87), 1,
      aux_sym_type_parameter_token1,
    STATE(12), 1,
      sym_type_identifier,
    STATE(10), 2,
      sym_type,
      aux_sym_constructor_repeat1,
    ACTIONS(49), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    STATE(33), 3,
      sym_sum_type,
      sym_product_type,
      sym_type_parameter,
  [283] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      anon_sym_LPAREN,
    ACTIONS(92), 1,
      anon_sym_LBRACE,
    ACTIONS(95), 1,
      aux_sym_constructor_name_token1,
    ACTIONS(98), 1,
      aux_sym_type_parameter_token1,
    STATE(12), 1,
      sym_type_identifier,
    STATE(10), 2,
      sym_type,
      aux_sym_constructor_repeat1,
    ACTIONS(33), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    STATE(33), 3,
      sym_sum_type,
      sym_product_type,
      sym_type_parameter,
  [316] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 1,
      anon_sym_LBRACE,
    ACTIONS(85), 1,
      aux_sym_constructor_name_token1,
    ACTIONS(87), 1,
      aux_sym_type_parameter_token1,
    STATE(12), 1,
      sym_type_identifier,
    STATE(9), 2,
      sym_type,
      aux_sym_constructor_repeat1,
    ACTIONS(65), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    STATE(33), 3,
      sym_sum_type,
      sym_product_type,
      sym_type_parameter,
  [349] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_LPAREN,
    ACTIONS(104), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      aux_sym_constructor_name_token1,
    ACTIONS(110), 1,
      aux_sym_type_parameter_token1,
    STATE(12), 1,
      sym_type_identifier,
    STATE(13), 2,
      sym_type,
      aux_sym_constructor_repeat1,
    ACTIONS(65), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    STATE(33), 3,
      sym_sum_type,
      sym_product_type,
      sym_type_parameter,
  [382] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(116), 1,
      anon_sym_LBRACE,
    ACTIONS(119), 1,
      aux_sym_constructor_name_token1,
    ACTIONS(122), 1,
      aux_sym_type_parameter_token1,
    STATE(12), 1,
      sym_type_identifier,
    STATE(10), 2,
      sym_type,
      aux_sym_constructor_repeat1,
    ACTIONS(49), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    STATE(33), 3,
      sym_sum_type,
      sym_product_type,
      sym_type_parameter,
  [415] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 3,
      anon_sym_type,
      anon_sym_alias,
      aux_sym_type_parameter_token1,
    ACTIONS(125), 8,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_constructor_name_token1,
  [434] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 3,
      anon_sym_type,
      anon_sym_alias,
      aux_sym_type_parameter_token1,
    ACTIONS(129), 8,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_constructor_name_token1,
  [453] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 3,
      anon_sym_type,
      anon_sym_alias,
      aux_sym_type_parameter_token1,
    ACTIONS(133), 8,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_constructor_name_token1,
  [472] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 3,
      anon_sym_type,
      anon_sym_alias,
      aux_sym_type_parameter_token1,
    ACTIONS(137), 8,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_constructor_name_token1,
  [491] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 3,
      anon_sym_type,
      anon_sym_alias,
      aux_sym_type_parameter_token1,
    ACTIONS(141), 8,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_constructor_name_token1,
  [510] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 3,
      anon_sym_type,
      anon_sym_alias,
      aux_sym_type_parameter_token1,
    ACTIONS(145), 8,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_constructor_name_token1,
  [529] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
    ACTIONS(151), 1,
      anon_sym_type,
    ACTIONS(154), 1,
      anon_sym_alias,
    ACTIONS(157), 1,
      aux_sym_type_parameter_token1,
    STATE(69), 1,
      sym_value_identifier,
    STATE(45), 2,
      sym_sum_type_definition,
      sym_alias_definition,
    STATE(20), 3,
      sym_type_definition,
      sym_value_definition,
      aux_sym_source_file_repeat1,
  [557] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_type,
    ACTIONS(9), 1,
      anon_sym_alias,
    ACTIONS(11), 1,
      aux_sym_type_parameter_token1,
    ACTIONS(160), 1,
      ts_builtin_sym_end,
    STATE(69), 1,
      sym_value_identifier,
    STATE(45), 2,
      sym_sum_type_definition,
      sym_alias_definition,
    STATE(20), 3,
      sym_type_definition,
      sym_value_definition,
      aux_sym_source_file_repeat1,
  [585] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(85), 1,
      aux_sym_constructor_name_token1,
    ACTIONS(87), 1,
      aux_sym_type_parameter_token1,
    STATE(11), 1,
      sym_type_identifier,
    STATE(83), 1,
      sym_type,
    STATE(14), 3,
      sym_sum_type,
      sym_product_type,
      sym_type_parameter,
  [612] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      aux_sym_constructor_name_token1,
    ACTIONS(162), 1,
      aux_sym_type_parameter_token1,
    STATE(7), 1,
      sym_type_identifier,
    STATE(46), 1,
      sym_type,
    STATE(14), 3,
      sym_sum_type,
      sym_product_type,
      sym_type_parameter,
  [639] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      aux_sym_constructor_name_token1,
    ACTIONS(162), 1,
      aux_sym_type_parameter_token1,
    STATE(7), 1,
      sym_type_identifier,
    STATE(53), 1,
      sym_type,
    STATE(14), 3,
      sym_sum_type,
      sym_product_type,
      sym_type_parameter,
  [666] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(85), 1,
      aux_sym_constructor_name_token1,
    ACTIONS(87), 1,
      aux_sym_type_parameter_token1,
    STATE(11), 1,
      sym_type_identifier,
    STATE(87), 1,
      sym_type,
    STATE(14), 3,
      sym_sum_type,
      sym_product_type,
      sym_type_parameter,
  [693] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(85), 1,
      aux_sym_constructor_name_token1,
    ACTIONS(87), 1,
      aux_sym_type_parameter_token1,
    STATE(11), 1,
      sym_type_identifier,
    STATE(77), 1,
      sym_type,
    STATE(14), 3,
      sym_sum_type,
      sym_product_type,
      sym_type_parameter,
  [720] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 8,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_constructor_name_token1,
      aux_sym_type_parameter_token1,
  [734] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 3,
      anon_sym_type,
      anon_sym_alias,
      aux_sym_type_parameter_token1,
    ACTIONS(166), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      aux_sym_constructor_name_token1,
  [750] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 8,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_constructor_name_token1,
      aux_sym_type_parameter_token1,
  [764] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 3,
      anon_sym_type,
      anon_sym_alias,
      aux_sym_type_parameter_token1,
    ACTIONS(170), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      aux_sym_constructor_name_token1,
  [780] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 3,
      anon_sym_type,
      anon_sym_alias,
      aux_sym_type_parameter_token1,
    ACTIONS(164), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      aux_sym_constructor_name_token1,
  [796] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_constructor_name_token1,
      aux_sym_type_parameter_token1,
  [809] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_constructor_name_token1,
      aux_sym_type_parameter_token1,
  [822] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_constructor_name_token1,
      aux_sym_type_parameter_token1,
  [835] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_constructor_name_token1,
      aux_sym_type_parameter_token1,
  [848] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_constructor_name_token1,
      aux_sym_type_parameter_token1,
  [861] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      aux_sym_constructor_name_token1,
      aux_sym_type_parameter_token1,
  [874] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      ts_builtin_sym_end,
    ACTIONS(180), 1,
      anon_sym_PIPE,
    STATE(41), 1,
      aux_sym_sum_type_definition_repeat2,
    ACTIONS(178), 3,
      anon_sym_type,
      anon_sym_alias,
      aux_sym_type_parameter_token1,
  [892] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      ts_builtin_sym_end,
    ACTIONS(180), 1,
      anon_sym_PIPE,
    STATE(42), 1,
      aux_sym_sum_type_definition_repeat2,
    ACTIONS(178), 3,
      anon_sym_type,
      anon_sym_alias,
      aux_sym_type_parameter_token1,
  [910] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      anon_sym_PIPE,
    ACTIONS(182), 1,
      ts_builtin_sym_end,
    STATE(38), 1,
      aux_sym_sum_type_definition_repeat2,
    ACTIONS(184), 3,
      anon_sym_type,
      anon_sym_alias,
      aux_sym_type_parameter_token1,
  [928] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      ts_builtin_sym_end,
    ACTIONS(190), 1,
      anon_sym_PIPE,
    STATE(41), 1,
      aux_sym_sum_type_definition_repeat2,
    ACTIONS(188), 3,
      anon_sym_type,
      anon_sym_alias,
      aux_sym_type_parameter_token1,
  [946] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      anon_sym_PIPE,
    ACTIONS(193), 1,
      ts_builtin_sym_end,
    STATE(41), 1,
      aux_sym_sum_type_definition_repeat2,
    ACTIONS(195), 3,
      anon_sym_type,
      anon_sym_alias,
      aux_sym_type_parameter_token1,
  [964] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 2,
      ts_builtin_sym_end,
      anon_sym_PIPE,
    ACTIONS(188), 3,
      anon_sym_type,
      anon_sym_alias,
      aux_sym_type_parameter_token1,
  [977] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      aux_sym_type_parameter_token1,
    ACTIONS(197), 1,
      anon_sym_EQ,
    STATE(54), 2,
      sym_type_parameter,
      aux_sym_sum_type_definition_repeat1,
  [991] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      ts_builtin_sym_end,
    ACTIONS(201), 3,
      anon_sym_type,
      anon_sym_alias,
      aux_sym_type_parameter_token1,
  [1003] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      ts_builtin_sym_end,
    ACTIONS(205), 3,
      anon_sym_type,
      anon_sym_alias,
      aux_sym_type_parameter_token1,
  [1015] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      aux_sym_type_parameter_token1,
    STATE(63), 1,
      sym_name_type_pair,
    STATE(84), 1,
      sym_type_parameter,
    STATE(85), 1,
      sym_field_identifier,
  [1031] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      ts_builtin_sym_end,
    ACTIONS(211), 3,
      anon_sym_type,
      anon_sym_alias,
      aux_sym_type_parameter_token1,
  [1043] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      ts_builtin_sym_end,
    ACTIONS(215), 3,
      anon_sym_type,
      anon_sym_alias,
      aux_sym_type_parameter_token1,
  [1055] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      ts_builtin_sym_end,
    ACTIONS(219), 3,
      anon_sym_type,
      anon_sym_alias,
      aux_sym_type_parameter_token1,
  [1067] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      aux_sym_type_parameter_token1,
    ACTIONS(221), 1,
      anon_sym_EQ,
    STATE(55), 2,
      sym_type_parameter,
      aux_sym_sum_type_definition_repeat1,
  [1081] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      aux_sym_type_parameter_token1,
    ACTIONS(223), 1,
      anon_sym_EQ,
    STATE(51), 2,
      sym_type_parameter,
      aux_sym_sum_type_definition_repeat1,
  [1095] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      ts_builtin_sym_end,
    ACTIONS(227), 3,
      anon_sym_type,
      anon_sym_alias,
      aux_sym_type_parameter_token1,
  [1107] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      aux_sym_type_parameter_token1,
    ACTIONS(229), 1,
      anon_sym_EQ,
    STATE(55), 2,
      sym_type_parameter,
      aux_sym_sum_type_definition_repeat1,
  [1121] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_EQ,
    ACTIONS(233), 1,
      aux_sym_type_parameter_token1,
    STATE(55), 2,
      sym_type_parameter,
      aux_sym_sum_type_definition_repeat1,
  [1135] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      aux_sym_type_parameter_token1,
    STATE(71), 1,
      sym_name_type_pair,
    STATE(85), 1,
      sym_field_identifier,
    STATE(89), 1,
      sym_type_parameter,
  [1151] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_COMMA,
    ACTIONS(238), 1,
      anon_sym_RBRACE,
    STATE(72), 1,
      aux_sym_product_type_repeat1,
  [1164] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      aux_sym_constructor_name_token1,
    STATE(3), 1,
      sym_constructor_name,
    STATE(40), 1,
      sym_constructor,
  [1177] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_COMMA,
    ACTIONS(242), 1,
      anon_sym_RBRACE,
    STATE(61), 1,
      aux_sym_product_type_repeat1,
  [1190] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_COMMA,
    ACTIONS(247), 1,
      anon_sym_RBRACE,
    STATE(60), 1,
      aux_sym_product_type_repeat1,
  [1203] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_COMMA,
    ACTIONS(249), 1,
      anon_sym_RBRACE,
    STATE(60), 1,
      aux_sym_product_type_repeat1,
  [1216] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      aux_sym_constructor_name_token1,
    STATE(3), 1,
      sym_constructor_name,
    STATE(39), 1,
      sym_constructor,
  [1229] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_COMMA,
    ACTIONS(251), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      aux_sym_product_type_repeat1,
  [1242] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      aux_sym_constructor_name_token1,
    STATE(3), 1,
      sym_constructor_name,
    STATE(43), 1,
      sym_constructor,
  [1255] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      anon_sym_EQ,
    ACTIONS(255), 1,
      sym_parameter,
    STATE(67), 1,
      aux_sym_value_definition_repeat1,
  [1268] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_COMMA,
    ACTIONS(257), 1,
      anon_sym_RBRACE,
    STATE(60), 1,
      aux_sym_product_type_repeat1,
  [1281] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_EQ,
    ACTIONS(261), 1,
      sym_parameter,
    STATE(67), 1,
      aux_sym_value_definition_repeat1,
  [1294] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      aux_sym_type_parameter_token1,
    STATE(75), 1,
      sym_name_type_pair,
    STATE(85), 1,
      sym_field_identifier,
  [1307] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_EQ,
    ACTIONS(268), 1,
      sym_parameter,
    STATE(65), 1,
      aux_sym_value_definition_repeat1,
  [1320] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_COMMA,
    ACTIONS(270), 1,
      anon_sym_RBRACE,
    STATE(60), 1,
      aux_sym_product_type_repeat1,
  [1333] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_COMMA,
    ACTIONS(272), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      aux_sym_product_type_repeat1,
  [1346] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_COMMA,
    ACTIONS(274), 1,
      anon_sym_RBRACE,
    STATE(60), 1,
      aux_sym_product_type_repeat1,
  [1359] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      aux_sym_type_parameter_token1,
    STATE(59), 1,
      sym_name_type_pair,
    STATE(85), 1,
      sym_field_identifier,
  [1372] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      aux_sym_type_parameter_token1,
    STATE(57), 1,
      sym_name_type_pair,
    STATE(85), 1,
      sym_field_identifier,
  [1385] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1393] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      aux_sym_constructor_name_token1,
    STATE(52), 1,
      sym_type_identifier,
  [1403] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1411] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      anon_sym_PIPE,
    ACTIONS(278), 1,
      anon_sym_COLON,
  [1421] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 2,
      anon_sym_EQ,
      sym_parameter,
  [1429] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      aux_sym_constructor_name_token1,
    STATE(44), 1,
      sym_type_identifier,
  [1439] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      sym_string,
    STATE(49), 1,
      sym_expression,
  [1449] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      sym_string,
    STATE(50), 1,
      sym_expression,
  [1459] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      anon_sym_RPAREN,
  [1466] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      anon_sym_PIPE,
  [1473] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      anon_sym_COLON,
  [1480] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 1,
      ts_builtin_sym_end,
  [1487] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      anon_sym_RPAREN,
  [1494] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      anon_sym_COLON,
  [1501] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 1,
      anon_sym_PIPE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 36,
  [SMALL_STATE(4)] = 72,
  [SMALL_STATE(5)] = 108,
  [SMALL_STATE(6)] = 144,
  [SMALL_STATE(7)] = 180,
  [SMALL_STATE(8)] = 215,
  [SMALL_STATE(9)] = 250,
  [SMALL_STATE(10)] = 283,
  [SMALL_STATE(11)] = 316,
  [SMALL_STATE(12)] = 349,
  [SMALL_STATE(13)] = 382,
  [SMALL_STATE(14)] = 415,
  [SMALL_STATE(15)] = 434,
  [SMALL_STATE(16)] = 453,
  [SMALL_STATE(17)] = 472,
  [SMALL_STATE(18)] = 491,
  [SMALL_STATE(19)] = 510,
  [SMALL_STATE(20)] = 529,
  [SMALL_STATE(21)] = 557,
  [SMALL_STATE(22)] = 585,
  [SMALL_STATE(23)] = 612,
  [SMALL_STATE(24)] = 639,
  [SMALL_STATE(25)] = 666,
  [SMALL_STATE(26)] = 693,
  [SMALL_STATE(27)] = 720,
  [SMALL_STATE(28)] = 734,
  [SMALL_STATE(29)] = 750,
  [SMALL_STATE(30)] = 764,
  [SMALL_STATE(31)] = 780,
  [SMALL_STATE(32)] = 796,
  [SMALL_STATE(33)] = 809,
  [SMALL_STATE(34)] = 822,
  [SMALL_STATE(35)] = 835,
  [SMALL_STATE(36)] = 848,
  [SMALL_STATE(37)] = 861,
  [SMALL_STATE(38)] = 874,
  [SMALL_STATE(39)] = 892,
  [SMALL_STATE(40)] = 910,
  [SMALL_STATE(41)] = 928,
  [SMALL_STATE(42)] = 946,
  [SMALL_STATE(43)] = 964,
  [SMALL_STATE(44)] = 977,
  [SMALL_STATE(45)] = 991,
  [SMALL_STATE(46)] = 1003,
  [SMALL_STATE(47)] = 1015,
  [SMALL_STATE(48)] = 1031,
  [SMALL_STATE(49)] = 1043,
  [SMALL_STATE(50)] = 1055,
  [SMALL_STATE(51)] = 1067,
  [SMALL_STATE(52)] = 1081,
  [SMALL_STATE(53)] = 1095,
  [SMALL_STATE(54)] = 1107,
  [SMALL_STATE(55)] = 1121,
  [SMALL_STATE(56)] = 1135,
  [SMALL_STATE(57)] = 1151,
  [SMALL_STATE(58)] = 1164,
  [SMALL_STATE(59)] = 1177,
  [SMALL_STATE(60)] = 1190,
  [SMALL_STATE(61)] = 1203,
  [SMALL_STATE(62)] = 1216,
  [SMALL_STATE(63)] = 1229,
  [SMALL_STATE(64)] = 1242,
  [SMALL_STATE(65)] = 1255,
  [SMALL_STATE(66)] = 1268,
  [SMALL_STATE(67)] = 1281,
  [SMALL_STATE(68)] = 1294,
  [SMALL_STATE(69)] = 1307,
  [SMALL_STATE(70)] = 1320,
  [SMALL_STATE(71)] = 1333,
  [SMALL_STATE(72)] = 1346,
  [SMALL_STATE(73)] = 1359,
  [SMALL_STATE(74)] = 1372,
  [SMALL_STATE(75)] = 1385,
  [SMALL_STATE(76)] = 1393,
  [SMALL_STATE(77)] = 1403,
  [SMALL_STATE(78)] = 1411,
  [SMALL_STATE(79)] = 1421,
  [SMALL_STATE(80)] = 1429,
  [SMALL_STATE(81)] = 1439,
  [SMALL_STATE(82)] = 1449,
  [SMALL_STATE(83)] = 1459,
  [SMALL_STATE(84)] = 1466,
  [SMALL_STATE(85)] = 1473,
  [SMALL_STATE(86)] = 1480,
  [SMALL_STATE(87)] = 1487,
  [SMALL_STATE(88)] = 1494,
  [SMALL_STATE(89)] = 1501,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constructor, 2, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constructor, 2, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_constructor, 2, 0, 0), SHIFT(30),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constructor, 1, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constructor, 1, 0, 0),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_constructor, 1, 0, 0), SHIFT(30),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_constructor_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_constructor_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constructor_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constructor_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constructor_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_constructor_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sum_type, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sum_type, 2, 0, 0),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_sum_type, 2, 0, 0), SHIFT(22),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_sum_type, 2, 0, 0), SHIFT(47),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_sum_type, 2, 0, 0), SHIFT(31),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_sum_type, 2, 0, 0), SHIFT(30),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sum_type, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sum_type, 1, 0, 0),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_sum_type, 1, 0, 0), SHIFT(22),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_sum_type, 1, 0, 0), SHIFT(47),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_sum_type, 1, 0, 0), SHIFT(31),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_sum_type, 1, 0, 0), SHIFT(30),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constructor_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constructor_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constructor_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constructor_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_sum_type, 1, 0, 0), SHIFT(25),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_sum_type, 1, 0, 0), SHIFT(56),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_sum_type, 1, 0, 0), SHIFT(27),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_sum_type, 1, 0, 0), SHIFT(29),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_sum_type, 2, 0, 0), SHIFT(25),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_sum_type, 2, 0, 0), SHIFT(56),
  [119] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_sum_type, 2, 0, 0), SHIFT(27),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_sum_type, 2, 0, 0), SHIFT(29),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_product_type, 6, 0, 1),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_product_type, 6, 0, 1),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_product_type, 5, 0, 1),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_product_type, 5, 0, 1),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_product_type, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_product_type, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_product_type, 4, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_product_type, 4, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [151] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [154] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [157] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_identifier, 1, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constructor_name, 1, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constructor_name, 1, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_parameter, 1, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_parameter, 1, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_identifier, 1, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sum_type_definition, 5, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sum_type_definition, 5, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sum_type_definition, 4, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sum_type_definition, 4, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sum_type_definition_repeat2, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_sum_type_definition_repeat2, 2, 0, 0),
  [190] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sum_type_definition_repeat2, 2, 0, 0), SHIFT_REPEAT(64),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sum_type_definition, 6, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sum_type_definition, 6, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 1, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_definition, 1, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_definition, 4, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alias_definition, 4, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_definition, 3, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value_definition, 3, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_definition, 4, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value_definition, 4, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias_definition, 5, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alias_definition, 5, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sum_type_definition_repeat1, 2, 0, 0),
  [233] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sum_type_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [244] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_product_type_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_product_type_repeat1, 2, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_value_definition_repeat1, 2, 0, 0),
  [261] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name_type_pair, 3, 0, 0),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_identifier, 1, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_identifier, 1, 0, 0),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [290] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_oakly(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
